export const HIDE_LOADINGPAGE='HIDE_LOADINGPAGE';
export const SHOW_LOADINGPAGE='SHOW_LOADINGPAGE';
export const HIDE_LOADINGSTATE='HIDE_LOADINGSTATE';
export const SHOW_LOADINGSTATE='SHOW_LOADINGSTATE';

export const FOOTER_SHOW='FOOTER_SHOW';
export const FOOTER_HIDE='FOOTER_HIDE';

export const CURRENT_CLUB_ID='CURRENT_CLUB_ID';